/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.views;

import br.com.DAO.ManutencaoDAO;
import br.com.DTO.ManutencaoDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Leon
 */
public class TelaGerenciaManutencao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaGerenciaManutencao
     */
    public TelaGerenciaManutencao() {
        initComponents();
        ManutencaoDAO dao = new ManutencaoDAO();
        dao.autoPesquisar();
        dao.verificaTipoGerenciamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbManu = new javax.swing.JTable();
        btnCria = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtIdEquip = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        txtSolucao = new javax.swing.JTextField();
        txtResponsa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(988, 623));
        setMinimumSize(new java.awt.Dimension(988, 623));
        setPreferredSize(new java.awt.Dimension(988, 623));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 49, 0));
        jLabel1.setText("gerenciamento de manutenção");

        tbManu.setBackground(new java.awt.Color(41, 37, 71));
        tbManu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbManu.setForeground(new java.awt.Color(255, 49, 0));
        tbManu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "equipamento", "data de registro", "diagnostico", "solução", "tecnico responsavel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbManu);

        btnCria.setBackground(new java.awt.Color(41, 37, 71));
        btnCria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnCria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriaActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(41, 37, 71));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(41, 37, 71));
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(41, 37, 71));
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remove.png"))); // NOI18N
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        txtId.setBackground(new java.awt.Color(41, 37, 71));
        txtId.setForeground(new java.awt.Color(255, 49, 0));

        txtIdEquip.setBackground(new java.awt.Color(41, 37, 71));
        txtIdEquip.setForeground(new java.awt.Color(255, 49, 0));

        txtData.setBackground(new java.awt.Color(41, 37, 71));
        txtData.setForeground(new java.awt.Color(255, 49, 0));

        txtDiagnostico.setBackground(new java.awt.Color(41, 37, 71));
        txtDiagnostico.setForeground(new java.awt.Color(255, 49, 0));

        txtSolucao.setBackground(new java.awt.Color(41, 37, 71));
        txtSolucao.setForeground(new java.awt.Color(255, 49, 0));

        txtResponsa.setBackground(new java.awt.Color(41, 37, 71));
        txtResponsa.setForeground(new java.awt.Color(255, 49, 0));

        jLabel2.setText("tecnico responsavel");

        jLabel3.setText("id");

        jLabel4.setText("id do equipamento");

        jLabel5.setText("data de registro");

        jLabel6.setText("diagnostico");

        jLabel7.setText("solução");

        jButton1.setBackground(new java.awt.Color(41, 37, 71));
        jButton1.setForeground(new java.awt.Color(255, 49, 0));
        jButton1.setText("limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResponsa, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnCria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)))
                .addGap(40, 40, 40)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(txtIdEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(txtResponsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCria, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jButton1))
                            .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(txtId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "escolha um id para pesquisar");
        } else {
            ManutencaoDAO dao = new ManutencaoDAO();
            ManutencaoDTO dto = new ManutencaoDTO();
            
            int id = Integer.parseInt(txtId.getText());
            
            dto.setId(id);
            
            dao.deletar(dto);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnCriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriaActionPerformed
        if (txtId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A manutenção necessita um id!");
        } else if (txtIdEquip.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A manutenção necessita um id de equipamento!");
        } else if (txtData.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A manutenção necessita uma data de registro!");
        } else if (txtResponsa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A manutenção necessita um tecnico responsave!");
        } else if (txtDiagnostico.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A manutenção necessita um diagnostico!");
        } else {
            ManutencaoDTO  dto= new ManutencaoDTO();
            ManutencaoDAO dao = new ManutencaoDAO();
            
            int idEquip = Integer.parseInt(txtIdEquip.getText());
            String data = txtData.getText();
            String responsa = txtResponsa.getText();
            String diagnostico = txtDiagnostico.getText();
            String solucao = txtSolucao.getText();
            int id = Integer.parseInt(txtId.getText());
            
            dto.setId(id);
            dto.setDiagnostico(diagnostico);
            dto.setDataManutencao(data);
            dto.setIdEquip(idEquip);
            dto.setSolucao(solucao);
            dto.setResponsavel(responsa);
            
            dao.criar(dto);
            
        }
    }//GEN-LAST:event_btnCriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManutencaoDAO dao = new ManutencaoDAO();
        dao.limparTudo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(txtId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "escolha um id para pesquisar");
        } else {
            ManutencaoDAO dao = new ManutencaoDAO();
            ManutencaoDTO dto = new ManutencaoDTO();
            
            int id = Integer.parseInt(txtId.getText());
            
            dto.setId(id);
            
            dao.pesquisar(dto);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (txtId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "selecione o id da manutenção que deve ser editada");
        } else if (txtIdEquip.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A manutenção necessita um id de equipamento!");
        } else if (txtData.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A manutenção necessita uma data de registro!");
        } else if (txtResponsa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A manutenção necessita um tecnico responsave!");
        } else if (txtDiagnostico.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A manutenção necessita um diagnostico!");
        } else {
            ManutencaoDTO  dto= new ManutencaoDTO();
            ManutencaoDAO dao = new ManutencaoDAO();
            
            int idEquip = Integer.parseInt(txtIdEquip.getText());
            String data = txtData.getText();
            String responsa = txtResponsa.getText();
            String diagnostico = txtDiagnostico.getText();
            String solucao = txtSolucao.getText();
            int id = Integer.parseInt(txtId.getText());
            
            dto.setId(id);
            dto.setDiagnostico(diagnostico);
            dto.setDataManutencao(data);
            dto.setIdEquip(idEquip);
            dto.setSolucao(solucao);
            dto.setResponsavel(responsa);
            
            dao.atualizar(dto);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAtualizar;
    public static javax.swing.JButton btnCria;
    public static javax.swing.JButton btnDeletar;
    public static javax.swing.JButton btnSearch;
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbManu;
    public static javax.swing.JTextField txtData;
    public static javax.swing.JTextField txtDiagnostico;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtIdEquip;
    public static javax.swing.JTextField txtResponsa;
    public static javax.swing.JTextField txtSolucao;
    // End of variables declaration//GEN-END:variables
}
